name: "Rewrite package.json"
description: "Rewrite package.json with specified version"
inputs:
  version:
    description: "Version to rewrite"
    required: true
  package_jsons:
    description: "package.jsons to rewrite"
    default: 'package.json'
  indent:
    description: '`tab` or number of spaces'
    default: tab
runs:
  using: "composite"
  steps:
    # バージョンをpackage.jsonに書き込み
    - name: Write version
      run: |
        # keep using ${{ inputs.package_jsons }} for array declaration
        declare -a package_jsons=(${{ inputs.package_jsons }})
        for package_json in ${package_jsons[@]}; do
          jq $INDENT_OPTION ".version = \"$VERSION\"" "${package_json}" > "${package_json}.tmp" && mv "${package_json}.tmp" "${package_json}"
        done
      shell: bash
      env:
        INDENT_OPTION: ${{ inputs.indent != 'tab' && format('--indent {0}', inputs.indent) || '--tab' }}
        VERSION: ${{ inputs.version }}
